POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John2",
    "email": "John2@j.com"
}
###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
   "client_id": "18a9e502-2dac-4178-a367-1ef818d57b28"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
   "Account_id_from": "da310605-5e64-42d2-aff3-d24eb5f9b1c8",
   "Account_id_to":"b0b8f75d-aa48-4a54-96d6-6eb95b2315e6",
   "amount": 100
   
}

